version: "3"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: local-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rmrf
      TZ: Asia/Seoul
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
