-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 22:12:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema muffin-plus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema muffin-plus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `muffin-plus` DEFAULT CHARACTER SET utf8 ;
USE `muffin-plus` ;

-- -----------------------------------------------------
-- Table `muffin-plus`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muffin-plus`.`user` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `type` TINYINT(10) NOT NULL,
    `date_created` DATETIME(3) NOT NULL,
    `date_updated` DATETIME(3) NOT NULL,
    `date_deleted` DATETIME(3) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muffin-plus`.`charging-station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muffin-plus`.`charging-station` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `status` TINYINT(10) NOT NULL,
    `chgerType` TINYINT(10) NOT NULL,
    `zcode` INT NOT NULL,
    `zscode` INT NOT NULL,
    `date_created` DATETIME(3) NOT NULL,
    `date_updated` DATETIME(3) NOT NULL,
    `date_deleted` DATETIME(3) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muffin-plus`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muffin-plus`.`reservation` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `charging_station_id` INT NOT NULL,
    `date_started` DATETIME(3) NULL,
    `date_ended` DATETIME(3) NULL,
    `date_created` DATETIME(3) NULL,
    `date_updated` DATETIME(3) NULL,
    `date_deleted` DATETIME(3) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
    UNIQUE INDEX `charging_station_id_UNIQUE` (`charging_station_id` ASC) VISIBLE
    );



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `user` (name, email, type, date_created, date_updated) VALUES ("kim", "test01@gmail.com", 0, "2023-03-27", "2023-03-27");
INSERT INTO `user` (name, email, type, date_created, date_updated) VALUES ("lee", "test02@gmail.com", 1, "2023-03-27", "2023-03-27");
INSERT INTO `user` (name, email, type, date_created, date_updated) VALUES ("park", "test03@gmail.com", 1, "2023-03-27", "2023-03-27");

INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin01", 2, 1, 11, 11590, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin02", 3, 2, 11, 11140, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin03", 3, 3, 11, 11170, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin04", 3, 1, 11, 11200, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin05", 4, 2, 11, 11590, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin06", 5, 3, 26, 26320, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin07", 3, 1, 26, 26290, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin08", 2, 2, 27, 27170, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin09", 2, 3, 27, 27140, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin10", 2, 1, 30, 30110, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin11", 3, 2, 30, 30140, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin12", 2, 3, 41, 41110, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin13", 3, 1, 41, 41130, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin14", 2, 2, 41, 41150, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin15", 3, 3, 11, 11410, "2023-03-27", "2023-03-27");
INSERT INTO `charging-station` (name, status, chgerType, zcode, zscode, date_created, date_updated) VALUES ("muffin16", 2, 1, 11, 11470, "2023-03-27", "2023-03-27");